# Generated by Django 4.0.5 on 2022-06-30 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, unique=True)),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('order', models.TextField(max_length=100)),
                ('order_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosu.position_master')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosu.project_master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosu.user_master')),
            ],
        ),
        migrations.CreateModel(
            name='Man_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.FloatField()),
                ('collect_date', models.DateField()),
                ('is_ss', models.BooleanField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosu.project_master')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosu.user_master')),
            ],
        ),
    ]
