# Generated by Django 4.0.5 on 2022-07-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_master',
            name='order',
            field=models.CharField(max_length=100),
        ),
    ]
